--- 
development: 
  adapter: mysql
  database: talia_demo_talia_development
  username: talia
  password: talia
  host: localhost
test: 
  adapter: mysql
  database: talia_demo_talia_test
  username: talia
  password: talia
  host: localhost
production: 
  adapter: mysql
  database: talia_demo_talia_production
  username: talia
  password: talia
  host: localhost
