--- 
production: 
  type: sesame
  location: ./sesame_production.db
  backend: native
test: 
  type: sesame
  location: ./sesame_test.db
  backend: native
development: 
  type: sesame
  url: http://babylon.netseven.it:9090/openrdf-sesame/repositories/talia_demo_development
  backend: http
