--- 
production: 
  type: sesame
  location: ./sesame_production.db
  backend: native
test: 
  type: sesame
  location: ./sesame_test.db
  backend: native
development: 
  type: sesame
  url: http://localhost:8080/openrdf-sesame/repositories/schopenhauer_dev
  backend: http     
#  location: ./sesame_development.db
#  backend: native
#  inferencing: true
